apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testproject-sb
  name: testproject-sb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testproject-sb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testproject-sb
    spec:
      containers:
      - image: mljmsacr.azurecr.io/testproject-sb:v1
        name: testproject-sb
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testproject-sb
  name: testproject-sb
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: testproject-sb
  type: LoadBalancer
status:
  loadBalancer: {}
